"""
Django settings for QLthuvien project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/topics/settings/
"""
# Tệp này chứa các cài đặt cấu hình chính cho dự án Django.
import os
from pathlib import Path
from decouple import config

# Đường dẫn gốc của dự án (tức là thư mục chứa manage.py)
BASE_DIR = Path(__file__).resolve().parent.parent


# Cài đặt phát triển nhanh - không phù hợp cho production
# Xem https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# CẢNH BÁO BẢO MẬT: giữ khóa bí mật được sử dụng trong sản xuất bí mật!
SECRET_KEY = config("SECRET_KEY", default='')

# CẢNH BÁO BẢO MẬT: không chạy với chế độ debug bật trong môi trường sản xuất!
DEBUG = config("DEBUG", default=True)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='').split(',')

# Cấu hình cho Codespaces (nếu bạn đang sử dụng GitHub Codespaces)
if 'CODESPACE_NAME' in os.environ:
    codespace_name = config("CODESPACE_NAME")
    codespace_domain = config("GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN")
    CSRF_TRUSTED_ORIGINS = [f'https://{codespace_name}-8000.{codespace_domain}']

# Định nghĩa ứng dụng
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_browser_reload",
    "src.library",
    "src.users",

]

# Middleware xử lý các yêu cầu và phản hồi HTTP
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

# Cho phép nhúng iframe từ nguồn này (quan trọng cho Codespaces)
X_FRAME_OPTIONS = "ALLOW-FROM preview.app.github.dev"

# URL gốc của dự án
ROOT_URLCONF = "src.urls" # Đã thay đổi từ QLthuvien.urls sang src.urls

# Cấu hình template
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "src" / "templates"], # Điều chỉnh đường dẫn template
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# Ứng dụng WSGI (Web Server Gateway Interface)
WSGI_APPLICATION = "src.wsgi.application"


# Cấu hình cơ sở dữ liệu
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3", # Sử dụng SQLite làm cơ sở dữ liệu mặc định
    }
}


# Xác thực mật khẩu
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Quốc tế hóa
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = "en-us" # Ngôn ngữ mặc định

TIME_ZONE = "UTC" # Múi giờ

USE_I18N = True # Hỗ trợ quốc tế hóa

USE_TZ = True # Hỗ trợ múi giờ


# Tệp tĩnh (CSS, JavaScript, Hình ảnh)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATICFILES_DIRS = [
    BASE_DIR / "src" / "static", # Điều chỉnh đường dẫn cho các tệp tĩnh
]

STATIC_URL = "static/" # URL cho các tệp tĩnh
STATIC_ROOT = BASE_DIR / "staticfiles" # Thư mục để thu thập các tệp tĩnh (khi triển khai)

# Cấu hình cho tệp media (upload của người dùng)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


# Loại khóa chính mặc định
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Cài đặt URL chuyển hướng sau khi đăng nhập/đăng xuất và URL cho trang đăng nhập
LOGIN_REDIRECT_URL = '/'  # Chuyển hướng về trang chủ sau khi đăng nhập thành công
LOGOUT_REDIRECT_URL = '/accounts/login/' # Chuyển hướng về trang đăng nhập sau khi đăng xuất
LOGIN_URL = '/accounts/login/' # URL mặc định mà Django sẽ chuyển hướng đến khi người dùng cần đăng nhập